[env:gateway]
platform = espressif32 @ 6.7.0
board = esp32dev
framework = arduino
build_src_filter = +<gateway/>
monitor_speed = 9600

lib_deps =
    painlessmesh/painlessMesh
    bblanchon/ArduinoJson@^7.0.4


[env:node]
platform = espressif32 @ 6.7.0
board = esp32dev
framework = arduino
build_src_filter = +<node/>
monitor_speed = 9600

lib_deps =
    painlessmesh/painlessMesh
    bblanchon/ArduinoJson@^7.0.4

[env:nodemcu]
platform = espressif8266
board = nodemcuv2
framework = arduino
build_src_filter = +<nodemcu/>
monitor_speed = 9600

lib_deps =
    painlessmesh/painlessMesh
    bblanchon/ArduinoJson@^7.0.4