[env:gateway]
platform = espressif32 @ 6.7.0
board = esp32dev
framework = arduino
build_src_filter = +<gateway/>
monitor_speed = 9600

lib_deps =
    painlessmesh/painlessMesh

[env:node]
platform = espressif32 @ 6.7.0
board = esp32dev
framework = arduino
build_src_filter = +<node/>
monitor_speed = 9600

lib_deps =
    painlessmesh/painlessMesh